[package]
name = "system-health"
version = "0.1.0"
authors = ["Lim Chia Hau <lch@lch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
